namespace Krilla.Html.Structure;

/// <summary>
/// What ARIA says about an element, for the structure tree.
/// </summary>
/// <remarks>
/// <para>
/// ARIA exists because HTML's own vocabulary runs out — a <c>&lt;div&gt;</c> is a heading when it
/// says so, and a document generated by a framework says so far more often than it reaches for
/// <c>&lt;h2&gt;</c>. A tag tree that reads only the element names therefore describes such a
/// document as a stack of anonymous divisions, which is exactly the shape a screen reader cannot
/// navigate.
/// </para>
/// <para>
/// Only the roles PDF has a structure type for are mapped. An unrecognised one falls back to the
/// element's own meaning rather than to nothing, which is what ARIA itself asks for and is also
/// the safe direction: <c>role="tooltip"</c> on a paragraph should still produce a paragraph.
/// </para>
/// </remarks>
static class AriaSemantics
{
    /// <summary>
    /// The structure element <paramref name="element"/>'s <c>role</c> asks for, or null when it
    /// declares none this maps.
    /// </summary>
    /// <remarks>
    /// ARIA allows a LIST of roles, the first supported one winning — a fallback chain written for
    /// readers that do not know the newest name. Taking the first this recognises is that rule.
    /// </remarks>
    public static TagNode? Role(IElement element)
    {
        if (element.GetAttribute("role") is not {Length: > 0} declared)
        {
            return null;
        }

        foreach (var role in declared.Split((char[]?) null, StringSplitOptions.RemoveEmptyEntries))
        {
            if (Map(role.ToLowerInvariant(), element) is {} node)
            {
                return node;
            }
        }

        return null;
    }

    static TagNode? Map(string role, IElement element) =>
        role switch
        {
            "heading" => new(Tag.Heading(Level(element), Name(element) ?? element.TextContent.Trim())),
            "list" => new(Tag.List(ListNumbering.Disc)),
            "listitem" => new(Tag.Create(TagKind.ListItem), Item: true),
            "table" or "grid" or "treegrid" => new(Tag.Create(TagKind.Table)),
            "rowgroup" => new(Tag.Create(TagKind.TableBody)),
            "row" => new(Tag.Create(TagKind.TableRow)),
            "cell" or "gridcell" => new(Tag.Create(TagKind.TableCell), Cell: true),
            "columnheader" => new(Tag.TableHeader(TableHeaderScope.Column), Cell: true),
            "rowheader" => new(Tag.TableHeader(TableHeaderScope.Row), Cell: true),
            "figure" or "img" or "image" => new(Tag.Figure(Picture(element))),
            "math" => new(Tag.Formula(Picture(element))),
            "link" => new(Tag.Create(TagKind.Link)),
            "paragraph" => new(Tag.Create(TagKind.Paragraph)),
            "article" or "main" or "document" => new(Tag.Create(TagKind.Article)),
            "region" or "group" or "navigation" or "banner" or "contentinfo" or "complementary"
                or "search" => new(Tag.Create(TagKind.Section)),
            "form" => new(Tag.Create(TagKind.Form)),
            "blockquote" => new(Tag.Create(TagKind.BlockQuote)),
            "code" => new(Tag.Create(TagKind.Code)),
            "strong" => new(Tag.Create(TagKind.Strong)),
            "emphasis" => new(Tag.Create(TagKind.Emphasis)),
            "note" or "doc-footnote" or "doc-endnote" => new(Tag.Create(TagKind.Note)),
            "caption" => new(Tag.Create(TagKind.Caption)),

            // "This element is presentation only": its own semantics are removed and its content
            // stays. PDF's NonStruct says exactly that, which is why the two map so cleanly.
            "presentation" or "none" => new(Tag.Create(TagKind.NonStructural)),
            _ => null
        };

    /// <summary>
    /// The level <c>role="heading"</c> carries.
    /// </summary>
    /// <remarks>
    /// ARIA's own default is 2 when <c>aria-level</c> is absent, on the reasoning that a heading
    /// declared this way is nearly always inside a document that already has a title. Clamped to
    /// HTML's own range: PDF 2.0 admits any <c>Hn</c>, PDF 1.7 admits H1 to H6, and a document
    /// asking for H9 is a mistyped attribute far more often than it is a nine-deep outline.
    /// </remarks>
    static int Level(IElement element)
    {
        if (element.GetAttribute("aria-level") is not {Length: > 0} declared ||
            !int.TryParse(declared, NumberStyles.Integer, CultureInfo.InvariantCulture, out var level))
        {
            return 2;
        }

        return Math.Clamp(level, 1, 6);
    }

    /// <summary>
    /// The accessible name ARIA gives <paramref name="element"/>, or null.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>aria-label</c> beats <c>aria-labelledby</c> here, where ARIA's own name computation has
    /// it the other way round. The reversal is deliberate: <c>aria-labelledby</c> resolves to the
    /// referenced elements' text, and text is exactly what a PDF reader already has — so an
    /// explicit label is the one saying something the page does not.
    /// </para>
    /// <para>
    /// A header cell's <c>abbr</c> is the last resort, and it is the one mapping here with no
    /// exact home in PDF. HTML calls it an alternative label for the cell, to be announced where
    /// repeating the whole header would be tedious; PDF 2.0 has <c>/Short</c> for precisely that
    /// and krilla exposes no setter for it, so it lands in <c>/Alt</c> — which a reader announces
    /// in place of the content everywhere rather than only where the header is referenced. The
    /// alternative was to drop it, and an author writing <c>abbr</c> wants the short form said.
    /// </para>
    /// </remarks>
    public static string? Name(IElement element)
    {
        if (Text(element.GetAttribute("aria-label")) is {} label)
        {
            return label;
        }

        if (Referenced(element, "aria-labelledby") is {} referenced)
        {
            return referenced;
        }

        return element.LocalName == "th" ? Text(element.GetAttribute("abbr")) : null;
    }

    /// <summary>
    /// The description ARIA gives <paramref name="element"/>, or null.
    /// </summary>
    public static string? Description(IElement element) =>
        Referenced(element, "aria-describedby");

    /// <summary>
    /// What a screen reader announces in place of a picture.
    /// </summary>
    /// <remarks>
    /// An <c>&lt;svg&gt;</c> has no <c>alt</c>, so its <c>&lt;title&gt;</c> child is read instead —
    /// which is where SVG itself puts the same information. An ARIA name outranks both, which is
    /// what ARIA asks for and what an author writing one means.
    /// </remarks>
    public static string? Picture(IElement element)
    {
        if (Name(element) is {} named)
        {
            return named;
        }

        if (Text(element.GetAttribute("alt")) is {} alt)
        {
            return alt;
        }

        if (element.QuerySelector("title") is {} title && Text(title.TextContent) is {} text)
        {
            return text;
        }

        return Text(element.GetAttribute("title"));
    }

    /// <summary>
    /// The expansion of an abbreviation, which is the one thing PDF has a field of its own for.
    /// </summary>
    /// <remarks>
    /// Two attributes look like candidates and only one is: <c>&lt;abbr title&gt;</c> is the LONG
    /// form of a short word, while <c>&lt;th abbr&gt;</c> is the SHORT form of a long header.
    /// <c>/E</c> is the EXPANSION, so writing a header's <c>abbr</c> into it would have a reader
    /// announce the short form in place of the long — the opposite of the field's purpose. A
    /// header's <c>abbr</c> goes to <see cref="Name"/> instead.
    /// </remarks>
    public static string? Expansion(IElement element)
    {
        if (element.LocalName is not ("abbr" or "acronym"))
        {
            return null;
        }

        return Text(element.GetAttribute("title"));
    }

    /// <summary>
    /// The text of the elements <paramref name="attribute"/> names, joined in the order named.
    /// </summary>
    /// <remarks>
    /// An id naming nothing is skipped rather than failing the whole attribute, which is what a
    /// browser does with the same markup.
    /// </remarks>
    static string? Referenced(IElement element, string attribute)
    {
        if (element.GetAttribute(attribute) is not {Length: > 0} declared ||
            element.Owner is not {} document)
        {
            return null;
        }

        var parts = new List<string>();

        foreach (var id in declared.Split((char[]?) null, StringSplitOptions.RemoveEmptyEntries))
        {
            if (document.GetElementById(id) is {} target &&
                Text(target.TextContent) is {} text)
            {
                parts.Add(text);
            }
        }

        return parts.Count == 0 ? null : string.Join(" ", parts);
    }

    /// <summary>The value with its white space collapsed, or null when it holds none.</summary>
    static string? Text(string? value)
    {
        if (value is null)
        {
            return null;
        }

        var collapsed = string.Join(
            " ",
            value.Split((char[]?) null, StringSplitOptions.RemoveEmptyEntries));

        return collapsed.Length == 0 ? null : collapsed;
    }
}
