global using System.IO.Compression;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Krilla.Html;
global using Krilla.Html.Diagnostics;
global using Krilla.Html.Fonts;
global using Morph.PDFium;
global using VerifyTests;
global using static VerifyTUnit.Verifier;
