/// <summary>
/// Finds presentational content attributes that are read and not applied, and reports them to
/// <see cref="HtmlOptions.OnDiagnostic"/>.
/// </summary>
/// <remarks>
/// <para>
/// HTML maps these onto CSS as presentational hints, at a specificity below every author rule.
/// AngleSharp does not apply that mapping, so an attribute here reaches the cascade as nothing at
/// all. <see cref="PresentationalHints"/> now performs the mapping for the attributes that have a
/// property to map onto; what is left here is the ones that do not.
/// </para>
/// <para>
/// They are worth reporting rather than dismissing as legacy. Documents converted to PDF are
/// disproportionately generated by reporting tools and mail merges, which emit exactly this markup
/// — and unlike an unimplemented CSS property, there is no stylesheet to inspect afterwards to
/// work out why the output looks wrong.
/// </para>
/// <para>
/// <c>width</c> and <c>height</c> on <c>&lt;img&gt;</c> are deliberately absent: those two ARE
/// applied, in <c>BoxBuilder.WithAttributeSize</c>. So is everything
/// <see cref="PresentationalHints"/> now maps — an attribute leaves this table on the commit that
/// starts honouring it, which is the only thing keeping the diagnostic invariant true.
/// </para>
/// </remarks>
static class UnsupportedAttributes
{
    const string notApplied = "not applied, because presentational attributes are not mapped onto CSS";

    static readonly Dictionary<string, string[]> byElement = new(StringComparer.Ordinal)
    {
        ["table"] = ["rules", "frame"],
        ["ol"] = ["type"],
        ["ul"] = ["type"],
        ["li"] = ["type"],
        ["hr"] = ["width", "size", "align", "color", "noshade"],
        ["font"] = ["color", "size", "face"],
        ["body"] = ["bgcolor", "text", "link", "vlink", "alink"],
        ["img"] = ["align", "border", "hspace", "vspace"]
    };

    public static void Report(IElement element, Action<HtmlDiagnostic> sink)
    {
        PresentationalHints.Report(element, sink);

        if (!byElement.TryGetValue(element.LocalName, out var attributes))
        {
            return;
        }

        foreach (var attribute in attributes)
        {
            if (element.GetAttribute(attribute) is {} value)
            {
                // A boolean attribute such as `nowrap` reads back as empty rather than absent.
                // Reported as a null value so it prints as the bare name it was written as.
                Diagnostic.Attribute(
                    sink,
                    element.LocalName,
                    attribute,
                    value.Length == 0 ? null : value,
                    notApplied);
            }
        }
    }
}
