namespace Krilla.Html;

/// <summary>
/// Finds presentational content attributes that are read and not applied, and reports them to
/// <see cref="HtmlOptions.OnDiagnostic"/>.
/// </summary>
/// <remarks>
/// <para>
/// HTML maps these onto CSS as presentational hints, at a specificity below every author rule.
/// AngleSharp does not apply that mapping, so an attribute here reaches the cascade as nothing at
/// all: a <c>&lt;table width="300"&gt;</c> lays out shrink-to-fit, and a
/// <c>&lt;td bgcolor="red"&gt;</c> paints no background.
/// </para>
/// <para>
/// They are worth reporting rather than dismissing as legacy. Documents converted to PDF are
/// disproportionately generated by reporting tools and mail merges, which emit exactly this markup
/// — and unlike an unimplemented CSS property, there is no stylesheet to inspect afterwards to
/// work out why the output looks wrong.
/// </para>
/// <para>
/// <c>width</c> and <c>height</c> on <c>&lt;img&gt;</c> are deliberately absent: those two ARE
/// applied, in <c>BoxBuilder.WithAttributeSize</c>.
/// </para>
/// </remarks>
static class UnsupportedAttributes
{
    const string notApplied = "not applied, because presentational attributes are not mapped onto the cascade";

    static readonly Dictionary<string, string[]> byElement = new(StringComparer.Ordinal)
    {
        ["table"] = ["width", "height", "border", "cellpadding", "cellspacing", "align", "bgcolor", "rules", "frame"],
        ["td"] = ["width", "height", "align", "valign", "bgcolor", "nowrap"],
        ["th"] = ["width", "height", "align", "valign", "bgcolor", "nowrap"],
        ["tr"] = ["height", "align", "valign", "bgcolor"],
        ["caption"] = ["align"],
        ["ol"] = ["type"],
        ["ul"] = ["type"],
        ["li"] = ["type"],
        ["p"] = ["align"],
        ["div"] = ["align"],
        ["h1"] = ["align"],
        ["h2"] = ["align"],
        ["h3"] = ["align"],
        ["h4"] = ["align"],
        ["h5"] = ["align"],
        ["h6"] = ["align"],
        ["hr"] = ["width", "size", "align", "color", "noshade"],
        ["font"] = ["color", "size", "face"],
        ["body"] = ["bgcolor", "text", "link", "vlink", "alink"],
        ["img"] = ["align", "border", "hspace", "vspace"]
    };

    public static void Report(IElement element, Action<HtmlDiagnostic> sink)
    {
        if (!byElement.TryGetValue(element.LocalName, out var attributes))
        {
            return;
        }

        foreach (var attribute in attributes)
        {
            if (element.GetAttribute(attribute) is {} value)
            {
                // A boolean attribute such as `nowrap` reads back as empty rather than absent.
                // Reported as a null value so it prints as the bare name it was written as.
                Diagnostic.Attribute(
                    sink,
                    element.LocalName,
                    attribute,
                    value.Length == 0 ? null : value,
                    notApplied);
            }
        }
    }
}
